const SET_AUTH_TRUE = 'SET_AUTH_TRUE';
const SET_AUTH_FALSE = 'SET_AUTH_FALSE';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const ADD_TASK = 'ADD_TASK';
const DONE_TASK = 'DONE_TASK';
export {
  SET_AUTH_TRUE,
  SET_AUTH_FALSE,
  UPDATE_TASK,
  DELETE_TASK,
  ADD_TASK,
  DONE_TASK,
};